object Versions {
    const val AGP = "8.0.2"
    const val KOTLIN = "1.8.10"
    const val ANDROID_CORE_KTX = "1.10.1"
    const val ACTIVITY_COMPOSE = "1.7.2"
    const val COMPOSE_BOM = "2023.06.01"
    const val LIFECYCLE = "2.6.1"
    const val NAVIGATION_COMPOSE = "2.6.0"
    const val COROUTINES_ANDROID = "1.7.3"
    const val MATERIAL3 = "1.2.0-alpha04"
    const val COMPOSE = "1.4.3"
    const val APPCOMPAT = "1.6.1"
    const val KOTLIN_BOM = "1.8.0"
    const val TEST_EXT_JUNIT = "1.1.5"
    const val TEST_ESPRESSO_CORE = "3.5.1"
    const val JUNIT = "4.13.2"
}