package com.teamwiney.core.common.model

enum class WineSmell(val type: String, val value: String, val korName: String) {
    FRUIT("FRUIT","FRUIT","과일향"),
    BERRY("FRUIT","BERRY", "베리류"),
    LEMON("FRUIT","LEMON","레몬"),
    LIME("FRUIT","LIME","라임"),
    APPLE("FRUIT","APPLE","사과"),
    PEAR("FRUIT","PEAR","배"),
    PEACH("FRUIT","PEACH","복숭아"),
    PLUM("FRUIT","PLUM","자두"),
    TROPICALFRUIT("FRUIT","TROPICALFRUIT","열대과일"),
    FLOWER("NATURAL", "FLOWER","꽃향"),
    ACACIA("NATURAL", "ACACIA", "아카시아"),
    ROSE("NATURAL", "ROSE", "장미"),
    LAVENDER("NATURAL", "LAVENDER", "라벤더"),
    GRASSWOOD("NATURAL", "GRASSWOOD","풀/나무"),
    PINE("NATURAL", "PINE", "솔향"),
    PEPPER("NATURAL", "PEPPER", "피망"),
    ONION("NATURAL", "ONION", "양파"),
    CORN("NATURAL", "CORN", "옥수수"),
    HERB("NATURAL","HERB","허브향"),
    MUSHROOM("NATURAL", "MUSHROOM", "버섯"),
    MOSS("NATURAL", "MOSS", "이끼"),
    OAK("OAK","OAK","오크향"),
    SPICE("OAK","SPICE","향신료"),
    PEPPERSPICE("OAK","PEPPERSPICE","후추"),
    CINNAMON("OAK", "CINNAMON", "계피"),
    NUTS("OAK","NUTS","견과류"),
    VANILLA("OAK","VANILLA","바닐라"),
    CARAMEL("OAK", "CARAMEL", "캐러멜"),
    CHOCOLATE("OAK","CHOCOLATE","초콜릿"),
    TOAST("OAK", "TOAST", "토스트"),
    COFFEE("OAK", "COFFEE", "커피"),
    COCONUT("OAK", "COCONUT", "코코넛"),
    SMOKE("OAK", "SMOKE", "연기"),
    FLINT("OTHER","FLINT","부싯돌"),
    BREAD("OTHER", "BREAD","빵"),
    RUBBER("OTHER","RUBBER","고무"),
    SWEAT("OTHER", "SWEAT", "땀"),
    LEATHER("OTHER", "LEATHER", "가죽"),
    VINEGAR("OTHER", "VINEGAR", "식초"),
    REMOVER("OTHER", "REMOVER", "리무버"),
    CIGARETTE("OTHER", "CIGARETTE", "담배"),
    HONEY("OTHER", "HONEY", "꿀"),
    BUTTER("OTHER", "BUTTER", "버터"),
    MEDICINE("OTHER", "MEDICINE","약품"),
    EARTHASH("OTHER","EARTHASH","흙/재")
}